
server:
    port: 3130 

security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
spring:
  redis:
    host: 127.0.0.1
    database: 0
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework: DEBUG    #开启debug信息：

